#!/bin/sh

# Find current working directory
CUR_DIR=`pwd`

# Include current working directory in path so that we can run script with name only
if [[ $SHELL == '/bin/csh' ]] ; then
	setenv PATH $CUR_DIR\:$PATH
elif [[ $SHELL == 'bin/sh' -o $SHELL == '/bin/bash' -o $SHELL == '/bin/zsh' ]] ; then
	export PATH=$CUR_DIR:$PATH

# Turn run scripts to executable
chmod +x run_*